import '../dbTypes/product_class.dart';

class ProductRepository {
  List<Product> getProducts() {
    return [
      // Difteria - Tétanos - Tos ferina (DTP)
      Vaccine(
        id: 'v_dtp',
        name: 'DTP',
        commonName: 'Difteria - Tétanos - Tos ferina',
        description:
            'Protección combinada contra Difteria, Tétanos y Tos ferina.',
        price: 40000.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/dtp.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 2,
        maxAge: 6,
        manufacturer: 'GENÉRICO',
        dosageInfo: '3 dosis: 2, 4 y 6 meses',
        expiryDate: DateTime(2026, 12, 31),
        storageInstructions: 'Mantener refrigerado entre 2-8°C',
        targetDiseases: 'Difteria, Tétanos y Tos ferina',
        dosesAndBoosters: '3 dosis',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),

      // Haemophilus Influenzae tipo b (Hib)
      Vaccine(
        id: 'v_hib',
        name: 'Hib',
        commonName: 'Haemophilus influenzae tipo b',
        description:
            'Protección contra enfermedades causadas por Haemophilus influenzae tipo b.',
        price: 30000.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/hib.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 2,
        maxAge: 6,
        manufacturer: 'GENÉRICO',
        dosageInfo: '3 dosis: 2, 4 y 6 meses',
        expiryDate: DateTime(2026, 12, 31),
        storageInstructions: 'Mantener refrigerado entre 2-8°C',
        targetDiseases: 'Meningitis, neumonía y otras por Hib',
        dosesAndBoosters: '3 dosis',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),

      // Hepatitis B
      Vaccine(
        id: 'v_hepb',
        name: 'Hepatitis B',
        commonName: 'Hepatitis B',
        description: 'Protección contra el virus de la Hepatitis B.',
        price: 25000.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/hepatitis_b.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 0,
        maxAge: 12,
        manufacturer: 'GENÉRICO',
        dosageInfo: '3 dosis: nacimiento, 2 y 6 meses',
        expiryDate: DateTime(2026, 12, 31),
        storageInstructions: 'Mantener refrigerado entre 2-8°C',
        targetDiseases: 'Hepatitis B',
        dosesAndBoosters: '3 dosis',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),

      // Pentavalente Package (DTP + Hib + Hepatitis B)
      Package(
        id: 'pkg_pentavalente',
        name: 'Vacuna Pentavalente',
        commonName: 'Pentavalente (DTP + Hib + Hepatitis B)',
        description:
            'Vacuna combinada para proteger contra Difteria, Tétanos, Tosferina, Hepatitis B y Haemophilus influenzae tipo b.',
        price: (40000.0 + 30000.0 + 25000.0) * 0.9, // 10% discount
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/pentavalente.png',
        applicableDoctors: ['Pediatría'],
        minAge: 2,
        maxAge: 6,
        specialIndications:
            'Este paquete aplica únicamente a menores entre 2 y 6 meses.',
        includedProductIds: ['v_dtp', 'v_hib', 'v_hepb'],
        targetMilestone: '2, 4 y 6 meses',
      ),
      // INFANRIX HEXA
      Vaccine(
        id: '1',
        name: 'INFANRIX HEXA',
        commonName: 'VACUNA HEXAVALENTE',
        description: 'Vacuna hexavalente para protección integral.',
        price: 130000.0,
        priceAvacunar: 135000.0,
        priceVita: 110000.0,
        priceColsanitas: 114300.0,
        imageUrl: 'lib/assets/images/products/infanrix_hexa.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 0,
        maxAge: 5,
        manufacturer: 'GSK',
        dosageInfo: 'Seguir protocolo de administración',
        expiryDate: DateTime(2025, 12, 31),
        storageInstructions: 'Mantener refrigerado entre 2-8°C',
        targetDiseases:
            'Vacuna diseñada para proteger a tu hij@ contra infecciones.',
        dosesAndBoosters: '3+1',
        specialIndications: 'Bebés prematuros, con indicación médica',
        contraindications: null,
        precautions: null,
      ),
      // PREVENAR 13
      Vaccine(
        id: '2',
        name: 'PREVENAR 13',
        commonName: 'CONJUGADA CONTRA NEUMOCOCO 13 SEROTIPOS',
        description: 'Vacuna conjugada para la prevención de neumococo.',
        price: 140000.0,
        priceAvacunar: 149000.0,
        priceVita: null,
        priceColsanitas: 134200.0,
        imageUrl: 'lib/assets/images/products/prevenar_13.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 0,
        maxAge: 5,
        manufacturer: 'PFIZER',
        dosageInfo: 'Seguir protocolo de administración',
        expiryDate: DateTime(2026, 6, 30),
        storageInstructions: 'Almacenar entre 2-8°C',
        targetDiseases: 'Protege a tu hijo contra la infección neumococo.',
        dosesAndBoosters: 'PAI 2+1 RECOMENDACION 3+1',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),
      // NIMENRIX
      Vaccine(
        id: '3',
        name: 'NIMENRIX',
        commonName: 'VACUNA ANTIMENINGOCOCCICA TETRACONJUGADA',
        description: 'Vacuna antimeningocócica tetrajugulada.',
        price: 150000.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/nimenrix.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 0,
        maxAge: 18,
        manufacturer: 'PFIZER',
        dosageInfo: 'Seguir protocolo de administración',
        expiryDate: DateTime(2026, 12, 31),
        storageInstructions: 'Mantener refrigerado',
        targetDiseases: 'Protege a tu hijo contra la bacteria Neisseria.',
        dosesAndBoosters: '6 sem - 6m 2+1 ; 6m-12m 1+1 ; >12 m 1',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),
      // INFLUVAC TETRA
      Vaccine(
        id: '4',
        name: 'INFLUVAC TETRA',
        commonName: 'VACUNA CUADRIVALENTE CONTRA INFLUENZA',
        description: 'Vacuna cuadrivalente para la prevención de la influenza.',
        price: 160000.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/influvac_tetra.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Medicina General'],
        minAge: 6,
        maxAge: 65,
        manufacturer: 'ABBOT',
        dosageInfo: 'Seguir protocolo de administración',
        expiryDate: DateTime(2025, 11, 15),
        storageInstructions: 'Mantener en refrigeración adecuada',
        targetDiseases:
            'Vacuna anual que protege a ti y a tu familia contra la influenza.',
        dosesAndBoosters: '2 dosis + refuerzo anual',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),
      // PRIORIX
      Vaccine(
        id: '5',
        name: 'PRIORIX',
        commonName: 'VACUNA TRIPLE VIRAL',
        description: 'Vacuna triple viral para la protección infantil.',
        price: 120000.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/priorix.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 1,
        maxAge: 18,
        manufacturer: 'GSK',
        dosageInfo: 'Seguir protocolo de administración',
        expiryDate: DateTime(2027, 8, 20),
        storageInstructions: 'Almacenar en lugar fresco y seco',
        targetDiseases: 'Vacuna que protege contra tres enfermedades virales.',
        dosesAndBoosters: '2 dosis (12 y 18 m)',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),
      // BOOSTRIX
      Vaccine(
        id: '6',
        name: 'BOOSTRIX (Difteria, Tosferina, Tetános -acelular)',
        commonName: 'BOOSTRIX',
        description:
            'Vacuna combinada para la protección contra difteria, tosferina y tetanos.',
        price: 85000.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/boostrix.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 0,
        maxAge: 5,
        manufacturer: 'GSK',
        dosageInfo: '2 dosis, 4 semanas de diferencia',
        expiryDate: DateTime(2025, 12, 31),
        storageInstructions: 'Mantener refrigerado entre 2-8°C',
        targetDiseases: 'Protege contra difteria, tosferina y tetanos.',
        dosesAndBoosters: '2 dosis',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),
      // FLUARIX
      Vaccine(
        id: '7',
        name: 'FLUARIX',
        commonName: 'FLUARIX',
        description: 'Vacuna contra la influenza (no ofertado).',
        price: 33250.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/fluarix.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Medicina General'],
        minAge: 6,
        maxAge: 65,
        manufacturer: 'Sanofi',
        dosageInfo: 'Una dosis anual',
        expiryDate: DateTime(2025, 11, 30),
        storageInstructions: 'Mantener en refrigeración adecuada',
        targetDiseases: 'Protege contra la influenza.',
        dosesAndBoosters: '1 dosis anual',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),
      // HAVRIX 720
      Vaccine(
        id: '8',
        name: 'HAVRIX 720 (Hepatitis A Niños)',
        commonName: 'HAVRIX 720',
        description: 'Vacuna para la prevención de Hepatitis A en niños.',
        price: 140000.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/havrix_72.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 1,
        maxAge: 12,
        manufacturer: 'GSK',
        dosageInfo: '2 dosis, 6-12 meses de diferencia',
        expiryDate: DateTime(2026, 6, 30),
        storageInstructions: 'Mantener refrigerado entre 2-8°C',
        targetDiseases: 'Protege contra la hepatitis A.',
        dosesAndBoosters: '2 dosis',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),
      // Rotarix
      Vaccine(
        id: '9',
        name: 'Rotarix',
        commonName: 'Rotarix',
        description:
            'Vacuna contra el rotavirus para prevenir gastroenteritis severa.',
        price: 90000.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/rotarix.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 0,
        maxAge: 12,
        manufacturer: 'GSK',
        dosageInfo: '2 dosis, a los 2 y 4 meses',
        expiryDate: DateTime(2026, 6, 30),
        storageInstructions: 'Mantener refrigerado entre 2-8°C',
        targetDiseases:
            'Protege contra la gastroenteritis severa causada por el rotavirus.',
        dosesAndBoosters: '2 dosis',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),
      // Menveo y Bexsero
      Vaccine(
        id: '10',
        name: 'Menveo y Bexsero',
        commonName: 'Menveo y Bexsero',
        description: 'Vacunas combinadas para la prevención de meningitis.',
        price: 150000.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/menveo_bexsero.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 0,
        maxAge: 18,
        manufacturer: 'GSK',
        dosageInfo: 'Seguir protocolo de administración',
        expiryDate: DateTime(2027, 12, 31),
        storageInstructions: 'Mantener refrigerado entre 2-8°C',
        targetDiseases: 'Protege contra varios serogrupos de meningococo.',
        dosesAndBoosters: '2 dosis',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),
      // TETRAXIM
      Vaccine(
        id: '11',
        name: 'TETRAXIM',
        commonName: 'TETRAXIM',
        description:
            'Vacuna combinada para la protección contra tétanos, difteria y tosferina.',
        price: 100000.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/tetraxim.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 0,
        maxAge: 5,
        manufacturer: 'Sanofi',
        dosageInfo: '2 dosis, 4 semanas de diferencia',
        expiryDate: DateTime(2026, 1, 31),
        storageInstructions: 'Mantener refrigerado entre 2-8°C',
        targetDiseases: 'Protege contra tétanos, difteria y tosferina.',
        dosesAndBoosters: '2 dosis',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),
      // VARICELA
      Vaccine(
        id: '12',
        name: 'VARICELA',
        commonName: 'VARICELA',
        description: 'Vacuna para la prevención de la varicela.',
        price: 110000.0,
        priceAvacunar: null,
        priceVita: null,
        priceColsanitas: null,
        imageUrl: 'lib/assets/images/products/varicela.png',
        category: ProductCategory.vaccine,
        applicableDoctors: ['Pediatría'],
        minAge: 1,
        maxAge: 12,
        manufacturer: 'Merck',
        dosageInfo: '1 o 2 dosis según protocolo',
        expiryDate: DateTime(2027, 6, 30),
        storageInstructions: 'Mantener refrigerado entre 2-8°C',
        targetDiseases: 'Protege contra la varicela.',
        dosesAndBoosters: '1-2 dosis',
        specialIndications: null,
        contraindications: null,
        precautions: null,
      ),
    ];
  }
}
